default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
        language_version: python3
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
        exclude: ^.*\.(lock)$
      - id: end-of-file-fixer
        exclude: ^.*\.(lock)$
      - id: mixed-line-ending
        exclude: ^.*\.(lock)$
      - id: detect-private-key
        exclude: fastcall/tests/integration/mock_authentication.py
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]
        stages: [commit-msg]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.3"
    hooks:
      - id: ruff
        name: Python lint
        files: ^fastcall/.*\.py$
        args: ["--fix"]

      - id: ruff-format
        name: Python format
        files: ^fastcall/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        name: Type checking
        args: [--config-file=pyproject.toml]
        exclude: tests/
        additional_dependencies:
          - types-cachetools
          - types-requests
          - types-ujson
          - types-toml
          - types-click
          - types-python-jose
          - pymongo
          - pydantic
          - fastapi
